spring:
  cloud:
    config:
      discovery:
        enabled:
          server: true
          serviceId: common-config #指定配置中心服务端的服务名称
      name: common-item #对应的{application}部分
      profile: dev #对应的{profile}部分
      uri: http://192.168.1.101:9000 #配置中心的具体体质，Greenwich版中需要添加
      label: master